
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLON COMMA EQUAL IDENTIFIER LBRACE RBRACE VALUE VARIABLEhash : IDENTIFIER EQUAL LBRACE key_value_pairs RBRACEkey_value_pairs : key_value_pairs COMMA key_value_pair\n                      | key_value_pair\n                      | emptykey_value_pair : IDENTIFIER COLON VALUE\n                        | empty\n    empty :\n    '
    
_lr_action_items = {'IDENTIFIER':([0,4,11,],[2,5,5,]),'$end':([1,10,],[0,-1,]),'EQUAL':([2,],[3,]),'LBRACE':([3,],[4,]),'RBRACE':([4,6,7,8,11,12,13,14,],[-7,10,-3,-4,-7,-5,-2,-6,]),'COMMA':([4,6,7,8,11,12,13,14,],[-7,11,-3,-4,-7,-5,-2,-6,]),'COLON':([5,],[9,]),'VALUE':([9,],[12,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'hash':([0,],[1,]),'key_value_pairs':([4,],[6,]),'key_value_pair':([4,11,],[7,13,]),'empty':([4,11,],[8,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> hash","S'",1,None,None,None),
  ('hash -> IDENTIFIER EQUAL LBRACE key_value_pairs RBRACE','hash',5,'p_hash','set_definition.py',37),
  ('key_value_pairs -> key_value_pairs COMMA key_value_pair','key_value_pairs',3,'p_key_value_pairs','set_definition.py',41),
  ('key_value_pairs -> key_value_pair','key_value_pairs',1,'p_key_value_pairs','set_definition.py',42),
  ('key_value_pairs -> empty','key_value_pairs',1,'p_key_value_pairs','set_definition.py',43),
  ('key_value_pair -> IDENTIFIER COLON VALUE','key_value_pair',3,'p_key_value_pair','set_definition.py',50),
  ('key_value_pair -> empty','key_value_pair',1,'p_key_value_pair','set_definition.py',51),
  ('empty -> <empty>','empty',0,'p_empty','set_definition.py',55),
]
